/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) roboracer_revised_bicycle_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {7, 1, 1};

/* roboracer_revised_bicycle_expl_vde_adj:(i0[5],i1[5],i2[2],i3[0])->(o0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w00=w+0, *w01=w+5, w02, w03, *w04=w+12, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, *w13=w+25;
  const casadi_real *cs;
  /* #0: @0 = zeros(5x1) */
  casadi_clear(w00, 5);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 5, w01);
  /* #2: @2 = @1[3] */
  for (rr=(&w02), cs=w01+3; cs!=w01+4; cs+=1) *rr++ = *cs;
  /* #3: @3 = 0.324 */
  w03 = 3.2400000000000001e-01;
  /* #4: @3 = (@2/@3) */
  w03  = (w02/w03);
  /* #5: @4 = input[1][0] */
  casadi_copy(arg[1], 5, w04);
  /* #6: {@5, @6, @7, @8, @9} = vertsplit(@4) */
  w05 = w04[0];
  w06 = w04[1];
  w07 = w04[2];
  w08 = w04[3];
  w09 = w04[4];
  /* #7: @3 = (@3*@7) */
  w03 *= w07;
  /* #8: @10 = @1[4] */
  for (rr=(&w10), cs=w01+4; cs!=w01+5; cs+=1) *rr++ = *cs;
  /* #9: @11 = cos(@10) */
  w11 = cos( w10 );
  /* #10: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #11: @3 = (@3/@11) */
  w03 /= w11;
  /* #12: (@0[4] += @3) */
  for (rr=w00+4, cs=(&w03); rr!=w00+5; rr+=1) *rr += *cs++;
  /* #13: @3 = @1[2] */
  for (rr=(&w03), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #14: @11 = cos(@3) */
  w11 = cos( w03 );
  /* #15: @12 = (@2*@6) */
  w12  = (w02*w06);
  /* #16: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #17: @3 = sin(@3) */
  w03 = sin( w03 );
  /* #18: @2 = (@2*@5) */
  w02 *= w05;
  /* #19: @2 = (@3*@2) */
  w02  = (w03*w02);
  /* #20: @12 = (@12-@2) */
  w12 -= w02;
  /* #21: (@0[2] += @12) */
  for (rr=w00+2, cs=(&w12); rr!=w00+3; rr+=1) *rr += *cs++;
  /* #22: @12 = 3.08642 */
  w12 = 3.0864197530864197e+00;
  /* #23: @10 = tan(@10) */
  w10 = tan( w10 );
  /* #24: @10 = (@10*@7) */
  w10 *= w07;
  /* #25: @12 = (@12*@10) */
  w12 *= w10;
  /* #26: @3 = (@3*@6) */
  w03 *= w06;
  /* #27: @12 = (@12+@3) */
  w12 += w03;
  /* #28: @11 = (@11*@5) */
  w11 *= w05;
  /* #29: @12 = (@12+@11) */
  w12 += w11;
  /* #30: (@0[3] += @12) */
  for (rr=w00+3, cs=(&w12); rr!=w00+4; rr+=1) *rr += *cs++;
  /* #31: output[0][0] = @0 */
  casadi_copy(w00, 5, res[0]);
  /* #32: @13 = zeros(2x1) */
  casadi_clear(w13, 2);
  /* #33: (@13[0] += @9) */
  for (rr=w13+0, cs=(&w09); rr!=w13+1; rr+=1) *rr += *cs++;
  /* #34: (@13[1] += @8) */
  for (rr=w13+1, cs=(&w08); rr!=w13+2; rr+=1) *rr += *cs++;
  /* #35: output[0][1] = @13 */
  if (res[0]) casadi_copy(w13, 2, res[0]+5);
  return 0;
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void roboracer_revised_bicycle_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void roboracer_revised_bicycle_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void roboracer_revised_bicycle_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void roboracer_revised_bicycle_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int roboracer_revised_bicycle_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int roboracer_revised_bicycle_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real roboracer_revised_bicycle_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* roboracer_revised_bicycle_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* roboracer_revised_bicycle_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* roboracer_revised_bicycle_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* roboracer_revised_bicycle_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 27;
  return 0;
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 27*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
