/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) roboracer_revised_bicycle_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[10] = 
  {2, 5, 0, 0, 0, 0, 1, 2,
  1, 0};
static const casadi_int casadi_s1[7] = {5, 2, 0, 1, 2, 4, 3};
static const casadi_int casadi_s2[13] = 
  {5, 2, 0, 4, 8, 0, 1, 2,
  4, 0, 1, 2, 3};
static const casadi_int casadi_s3[11] = 
  {5, 2, 0, 3, 6, 0, 1, 2,
  0, 1, 2};
static const casadi_int casadi_s4[3] = {5, 1, 1};
static const casadi_int casadi_s5[3] = {5, 5, 1};
static const casadi_int casadi_s6[3] = {5, 2, 1};
static const casadi_int casadi_s7[3] = {2, 1, 1};
static const casadi_int casadi_s8[3] = {0, 1, 1};
static const casadi_int casadi_s9[23] = 
  {5, 5, 0, 3, 6, 9, 12, 15,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 0, 1, 2};

static const casadi_real casadi_zeros[25] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* roboracer_revised_bicycle_expl_vde_forw:(i0[5],i1[5x5],i2[5x2],i3[2],i4[0])->(o0[5],o1[5x5,15nz],o2[5x2,8nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+5, w01, w02, w03, w04, w05, w06, w07, *w08=w+17, w14, w15;
  casadi_real w16, w17, *w19=w+68, *w20=w+70, *w21=w+72, *w23=w+90, *w24=w+93, *w25=w+96, *w26=w+102;
  const casadi_real *cs, *wr00, *wr09, *wr10, *wr11, *wr12, *wr13, *wr22;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 5, w00);
  /* #1: @1 = @0[3] */
  for (rr=(&w01), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #2: @2 = @0[2] */
  for (rr=(&w02), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #3: @3 = cos(@2) */
  w03 = cos( w02 );
  /* #4: @4 = (@1*@3) */
  w04  = (w01*w03);
  /* #5: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #6: @2 = sin(@2) */
  w02 = sin( w02 );
  /* #7: @4 = (@1*@2) */
  w04  = (w01*w02);
  /* #8: output[0][1] = @4 */
  if (res[0]) res[0][1] = w04;
  /* #9: @4 = 0.324 */
  w04 = 3.2400000000000001e-01;
  /* #10: @4 = (@1/@4) */
  w04  = (w01/w04);
  /* #11: @5 = @0[4] */
  for (rr=(&w05), cs=w00+4; cs!=w00+5; cs+=1) *rr++ = *cs;
  /* #12: @6 = tan(@5) */
  w06 = tan( w05 );
  /* #13: @7 = (@4*@6) */
  w07  = (w04*w06);
  /* #14: output[0][2] = @7 */
  if (res[0]) res[0][2] = w07;
  /* #15: @8 = input[3][0] */
  casadi_copy(arg[3], 2, w08);
  /* #16: @7 = @8[1] */
  for (rr=(&w07), cs=w08+1; cs!=w08+2; cs+=1) *rr++ = *cs;
  /* #17: output[0][3] = @7 */
  if (res[0]) res[0][3] = w07;
  /* #18: @7 = @8[0] */
  for (rr=(&w07), cs=w08+0; cs!=w08+1; cs+=1) *rr++ = *cs;
  /* #19: output[0][4] = @7 */
  if (res[0]) res[0][4] = w07;
  /* #20: @9 = input[1][0] */
  wr09 = arg[1] ? arg[1] : casadi_zeros;
  /* #21: {@0, @10, @11, @12, @13} = horzsplit(@9) */
  wr00 = wr09;
  wr10 = wr09+5;
  wr11 = wr09+10;
  wr12 = wr09+15;
  wr13 = wr09+20;
  /* #22: @7 = @0[3] */
  w07 = wr00[3];
  /* #23: @14 = (@3*@7) */
  w14  = (w03*w07);
  /* #24: @15 = @0[2] */
  w15 = wr00[2];
  /* #25: @16 = (@2*@15) */
  w16  = (w02*w15);
  /* #26: @16 = (@1*@16) */
  w16  = (w01*w16);
  /* #27: @14 = (@14-@16) */
  w14 -= w16;
  /* #28: output[1][0] = @14 */
  if (res[1]) res[1][0] = w14;
  /* #29: @14 = (@2*@7) */
  w14  = (w02*w07);
  /* #30: @15 = (@3*@15) */
  w15  = (w03*w15);
  /* #31: @15 = (@1*@15) */
  w15  = (w01*w15);
  /* #32: @14 = (@14+@15) */
  w14 += w15;
  /* #33: output[1][1] = @14 */
  if (res[1]) res[1][1] = w14;
  /* #34: @14 = 3.08642 */
  w14 = 3.0864197530864197e+00;
  /* #35: @7 = (@14*@7) */
  w07  = (w14*w07);
  /* #36: @7 = (@6*@7) */
  w07  = (w06*w07);
  /* #37: @15 = @0[4] */
  w15 = wr00[4];
  /* #38: @5 = cos(@5) */
  w05 = cos( w05 );
  /* #39: @5 = sq(@5) */
  w05 = casadi_sq( w05 );
  /* #40: @15 = (@15/@5) */
  w15 /= w05;
  /* #41: @15 = (@4*@15) */
  w15  = (w04*w15);
  /* #42: @7 = (@7+@15) */
  w07 += w15;
  /* #43: output[1][2] = @7 */
  if (res[1]) res[1][2] = w07;
  /* #44: @7 = @10[3] */
  w07 = wr10[3];
  /* #45: @15 = (@3*@7) */
  w15  = (w03*w07);
  /* #46: @16 = @10[2] */
  w16 = wr10[2];
  /* #47: @17 = (@2*@16) */
  w17  = (w02*w16);
  /* #48: @17 = (@1*@17) */
  w17  = (w01*w17);
  /* #49: @15 = (@15-@17) */
  w15 -= w17;
  /* #50: output[1][3] = @15 */
  if (res[1]) res[1][3] = w15;
  /* #51: @15 = (@2*@7) */
  w15  = (w02*w07);
  /* #52: @16 = (@3*@16) */
  w16  = (w03*w16);
  /* #53: @16 = (@1*@16) */
  w16  = (w01*w16);
  /* #54: @15 = (@15+@16) */
  w15 += w16;
  /* #55: output[1][4] = @15 */
  if (res[1]) res[1][4] = w15;
  /* #56: @7 = (@14*@7) */
  w07  = (w14*w07);
  /* #57: @7 = (@6*@7) */
  w07  = (w06*w07);
  /* #58: @15 = @10[4] */
  w15 = wr10[4];
  /* #59: @15 = (@15/@5) */
  w15 /= w05;
  /* #60: @15 = (@4*@15) */
  w15  = (w04*w15);
  /* #61: @7 = (@7+@15) */
  w07 += w15;
  /* #62: output[1][5] = @7 */
  if (res[1]) res[1][5] = w07;
  /* #63: @7 = @11[3] */
  w07 = wr11[3];
  /* #64: @15 = (@3*@7) */
  w15  = (w03*w07);
  /* #65: @16 = @11[2] */
  w16 = wr11[2];
  /* #66: @17 = (@2*@16) */
  w17  = (w02*w16);
  /* #67: @17 = (@1*@17) */
  w17  = (w01*w17);
  /* #68: @15 = (@15-@17) */
  w15 -= w17;
  /* #69: output[1][6] = @15 */
  if (res[1]) res[1][6] = w15;
  /* #70: @15 = (@2*@7) */
  w15  = (w02*w07);
  /* #71: @16 = (@3*@16) */
  w16  = (w03*w16);
  /* #72: @16 = (@1*@16) */
  w16  = (w01*w16);
  /* #73: @15 = (@15+@16) */
  w15 += w16;
  /* #74: output[1][7] = @15 */
  if (res[1]) res[1][7] = w15;
  /* #75: @7 = (@14*@7) */
  w07  = (w14*w07);
  /* #76: @7 = (@6*@7) */
  w07  = (w06*w07);
  /* #77: @15 = @11[4] */
  w15 = wr11[4];
  /* #78: @15 = (@15/@5) */
  w15 /= w05;
  /* #79: @15 = (@4*@15) */
  w15  = (w04*w15);
  /* #80: @7 = (@7+@15) */
  w07 += w15;
  /* #81: output[1][8] = @7 */
  if (res[1]) res[1][8] = w07;
  /* #82: @7 = @12[3] */
  w07 = wr12[3];
  /* #83: @15 = (@3*@7) */
  w15  = (w03*w07);
  /* #84: @16 = @12[2] */
  w16 = wr12[2];
  /* #85: @17 = (@2*@16) */
  w17  = (w02*w16);
  /* #86: @17 = (@1*@17) */
  w17  = (w01*w17);
  /* #87: @15 = (@15-@17) */
  w15 -= w17;
  /* #88: output[1][9] = @15 */
  if (res[1]) res[1][9] = w15;
  /* #89: @15 = (@2*@7) */
  w15  = (w02*w07);
  /* #90: @16 = (@3*@16) */
  w16  = (w03*w16);
  /* #91: @16 = (@1*@16) */
  w16  = (w01*w16);
  /* #92: @15 = (@15+@16) */
  w15 += w16;
  /* #93: output[1][10] = @15 */
  if (res[1]) res[1][10] = w15;
  /* #94: @7 = (@14*@7) */
  w07  = (w14*w07);
  /* #95: @7 = (@6*@7) */
  w07  = (w06*w07);
  /* #96: @15 = @12[4] */
  w15 = wr12[4];
  /* #97: @15 = (@15/@5) */
  w15 /= w05;
  /* #98: @15 = (@4*@15) */
  w15  = (w04*w15);
  /* #99: @7 = (@7+@15) */
  w07 += w15;
  /* #100: output[1][11] = @7 */
  if (res[1]) res[1][11] = w07;
  /* #101: @7 = @13[3] */
  w07 = wr13[3];
  /* #102: @15 = (@3*@7) */
  w15  = (w03*w07);
  /* #103: @16 = @13[2] */
  w16 = wr13[2];
  /* #104: @17 = (@2*@16) */
  w17  = (w02*w16);
  /* #105: @17 = (@1*@17) */
  w17  = (w01*w17);
  /* #106: @15 = (@15-@17) */
  w15 -= w17;
  /* #107: output[1][12] = @15 */
  if (res[1]) res[1][12] = w15;
  /* #108: @15 = (@2*@7) */
  w15  = (w02*w07);
  /* #109: @16 = (@3*@16) */
  w16  = (w03*w16);
  /* #110: @16 = (@1*@16) */
  w16  = (w01*w16);
  /* #111: @15 = (@15+@16) */
  w15 += w16;
  /* #112: output[1][13] = @15 */
  if (res[1]) res[1][13] = w15;
  /* #113: @7 = (@14*@7) */
  w07  = (w14*w07);
  /* #114: @7 = (@6*@7) */
  w07  = (w06*w07);
  /* #115: @15 = @13[4] */
  w15 = wr13[4];
  /* #116: @15 = (@15/@5) */
  w15 /= w05;
  /* #117: @15 = (@4*@15) */
  w15  = (w04*w15);
  /* #118: @7 = (@7+@15) */
  w07 += w15;
  /* #119: output[1][14] = @7 */
  if (res[1]) res[1][14] = w07;
  /* #120: @8 = zeros(2x5,2nz) */
  casadi_clear(w08, 2);
  /* #121: @18 = 00 */
  /* #122: @7 = 1 */
  w07 = 1.;
  /* #123: @19 = vertcat(@18, @18, @18, @7, @7) */
  rr=w19;
  *rr++ = w07;
  *rr++ = w07;
  /* #124: @20 = @19[:2] */
  for (rr=w20, cs=w19+0; cs!=w19+2; cs+=1) *rr++ = *cs;
  /* #125: (@8[:2] = @20) */
  for (rr=w08+0, cs=w20; rr!=w08+2; rr+=1) *rr = *cs++;
  /* #126: @20 = @8' */
  casadi_trans(w08,casadi_s0, w20, casadi_s1, iw);
  /* #127: @21 = project(@20) */
  casadi_project(w20, casadi_s1, w21, casadi_s2, w);
  /* #128: @22 = input[2][0] */
  wr22 = arg[2] ? arg[2] : casadi_zeros;
  /* #129: {@13, @12} = horzsplit(@22) */
  wr13 = wr22;
  wr12 = wr22+5;
  /* #130: @7 = @13[3] */
  w07 = wr13[3];
  /* #131: @15 = (@3*@7) */
  w15  = (w03*w07);
  /* #132: @16 = @13[2] */
  w16 = wr13[2];
  /* #133: @17 = (@2*@16) */
  w17  = (w02*w16);
  /* #134: @17 = (@1*@17) */
  w17  = (w01*w17);
  /* #135: @15 = (@15-@17) */
  w15 -= w17;
  /* #136: @17 = (@2*@7) */
  w17  = (w02*w07);
  /* #137: @16 = (@3*@16) */
  w16  = (w03*w16);
  /* #138: @16 = (@1*@16) */
  w16  = (w01*w16);
  /* #139: @17 = (@17+@16) */
  w17 += w16;
  /* #140: @7 = (@14*@7) */
  w07  = (w14*w07);
  /* #141: @7 = (@6*@7) */
  w07  = (w06*w07);
  /* #142: @16 = @13[4] */
  w16 = wr13[4];
  /* #143: @16 = (@16/@5) */
  w16 /= w05;
  /* #144: @16 = (@4*@16) */
  w16  = (w04*w16);
  /* #145: @7 = (@7+@16) */
  w07 += w16;
  /* #146: @23 = vertcat(@15, @17, @7, @18, @18) */
  rr=w23;
  *rr++ = w15;
  *rr++ = w17;
  *rr++ = w07;
  /* #147: @15 = @12[3] */
  w15 = wr12[3];
  /* #148: @17 = (@3*@15) */
  w17  = (w03*w15);
  /* #149: @7 = @12[2] */
  w07 = wr12[2];
  /* #150: @16 = (@2*@7) */
  w16  = (w02*w07);
  /* #151: @16 = (@1*@16) */
  w16  = (w01*w16);
  /* #152: @17 = (@17-@16) */
  w17 -= w16;
  /* #153: @2 = (@2*@15) */
  w02 *= w15;
  /* #154: @3 = (@3*@7) */
  w03 *= w07;
  /* #155: @1 = (@1*@3) */
  w01 *= w03;
  /* #156: @2 = (@2+@1) */
  w02 += w01;
  /* #157: @14 = (@14*@15) */
  w14 *= w15;
  /* #158: @6 = (@6*@14) */
  w06 *= w14;
  /* #159: @14 = @12[4] */
  w14 = wr12[4];
  /* #160: @14 = (@14/@5) */
  w14 /= w05;
  /* #161: @4 = (@4*@14) */
  w04 *= w14;
  /* #162: @6 = (@6+@4) */
  w06 += w04;
  /* #163: @24 = vertcat(@17, @2, @6, @18, @18) */
  rr=w24;
  *rr++ = w17;
  *rr++ = w02;
  *rr++ = w06;
  /* #164: @25 = horzcat(@23, @24) */
  rr=w25;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #165: @26 = project(@25) */
  casadi_project(w25, casadi_s3, w26, casadi_s2, w);
  /* #166: @21 = (@21+@26) */
  for (i=0, rr=w21, cs=w26; i<8; ++i) (*rr++) += (*cs++);
  /* #167: output[2][0] = @21 */
  casadi_copy(w21, 8, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void roboracer_revised_bicycle_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void roboracer_revised_bicycle_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void roboracer_revised_bicycle_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void roboracer_revised_bicycle_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int roboracer_revised_bicycle_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int roboracer_revised_bicycle_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real roboracer_revised_bicycle_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* roboracer_revised_bicycle_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* roboracer_revised_bicycle_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* roboracer_revised_bicycle_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* roboracer_revised_bicycle_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 110;
  return 0;
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 110*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
