/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {7, 1, 1};
static const casadi_int casadi_s5[17] = 
  {7, 7, 0, 1, 2, 3, 4, 5,
  6, 7, 2, 3, 4, 5, 6, 0,
  1};
static const casadi_int casadi_s6[3] = {7, 0, 1};

/* roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt:(i0[5],i1[2],i2[0],i3[],i4[0])->(o0[7],o1[7x7,7nz],o2[7x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w00=w+0, w01, *w02=w+6, *w03=w+8, *w04=w+15, w05, w06, w07, w08, w09, w10;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 5, w00);
  /* #1: @1 = @0[0] */
  for (rr=(&w01), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #3: @1 = @0[1] */
  for (rr=(&w01), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w01;
  /* #5: @1 = @0[2] */
  for (rr=(&w01), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #6: output[0][2] = @1 */
  if (res[0]) res[0][2] = w01;
  /* #7: @1 = @0[3] */
  for (rr=(&w01), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #8: output[0][3] = @1 */
  if (res[0]) res[0][3] = w01;
  /* #9: @1 = @0[4] */
  for (rr=(&w01), cs=w00+4; cs!=w00+5; cs+=1) *rr++ = *cs;
  /* #10: output[0][4] = @1 */
  if (res[0]) res[0][4] = w01;
  /* #11: @2 = input[1][0] */
  casadi_copy(arg[1], 2, w02);
  /* #12: @1 = @2[0] */
  for (rr=(&w01), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #13: output[0][5] = @1 */
  if (res[0]) res[0][5] = w01;
  /* #14: @1 = @2[1] */
  for (rr=(&w01), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #15: output[0][6] = @1 */
  if (res[0]) res[0][6] = w01;
  /* #16: @3 = zeros(7x7,7nz) */
  casadi_clear(w03, 7);
  /* #17: @4 = ones(7x1) */
  casadi_fill(w04, 7, 1.);
  /* #18: {@2, @0} = vertsplit(@4) */
  casadi_copy(w04, 2, w02);
  casadi_copy(w04+2, 5, w00);
  /* #19: @1 = @0[0] */
  for (rr=(&w01), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #20: @5 = @0[1] */
  for (rr=(&w05), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #21: @6 = @0[2] */
  for (rr=(&w06), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #22: @7 = @0[3] */
  for (rr=(&w07), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #23: @8 = @0[4] */
  for (rr=(&w08), cs=w00+4; cs!=w00+5; cs+=1) *rr++ = *cs;
  /* #24: @9 = @2[0] */
  for (rr=(&w09), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #25: @10 = @2[1] */
  for (rr=(&w10), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #26: @4 = vertcat(@1, @5, @6, @7, @8, @9, @10) */
  rr=w04;
  *rr++ = w01;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  /* #27: (@3[:7] = @4) */
  for (rr=w03+0, cs=w04; rr!=w03+7; rr+=1) *rr = *cs++;
  /* #28: output[1][0] = @3 */
  casadi_copy(w03, 7, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 28;
  return 0;
}

CASADI_SYMBOL_EXPORT int roboracer_revised_bicycle_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 28*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
